server:
  port: 7060
spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      url: mongodb://localhost:27017
      database: microservices
  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registery: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka
      